name: Check for LÖVE version update & update if theres a new version

on:
  schedule:
    - cron: '0 0 12 1 */2 *' #At 12:00 PM, on day 1 of the month, every 2 months
  workflow_dispatch:

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install Lua 5.4
        run: sudo apt-get install lua5.4 curl grep -y
        
      - name: Update README.md
        run: lua update_readme.lua