name: Check for LÖVE version update & update if theres a new version

on:
  schedule:
    - cron: '0 0 1 * *' # Runs the workflow on the 1st day of every month at midnight UTC
  workflow_dispatch: # Manually triggered workflow

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl grep
        
      - name: Extract LÖVE version from love2d.org
        id: extract_version
        run: |
          VERSION=$(curl -s https://love2d.org/ | grep -oP '<h2>Download LÖVE \K[0-9]+\.[0-9]+')
          echo "::set-output name=version::$VERSION"
          
      - name: Compare with latest version
        id: compare_versions
        run: |
          LATEST_VERSION=$(cat latest-version.txt)
          if [ "$LATEST_VERSION" != "${{ steps.extract_version.outputs.version }}" ]; then
            echo "LÖVE version updated."
            echo "${{ steps.extract_version.outputs.version }}" > latest-version.txt
          else
            echo "LÖVE version unchanged."
            exit 1
          fi

  mirror_website:
    needs: check_version
    if: failure() # Only runs if the version check fails
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install HTTrack
        run: sudo apt-get install httrack -y
        
      - name: Mirror love2d.org
        run: httrack https://love2d.org/ -O ./love2d.org
        
      - name: Update latest version
        run: echo ::set-output name=version::$(cat latest-version.txt)
        
      - name: Update README.md
        uses: actions/github-script@v5
        with:
          script: |
            const fs = require('fs');
            let readmeContent = fs.readFileSync('README.md', 'utf8');
            readmeContent = readmeContent.replace(/!\[LOVE\]\(https:\/\/img\.shields\.io\/badge\/L%C3%96VE-[0-9]+\.[0-9]+-EA316E\.svg\?style=flat-square\)/, `![LOVE](https://img.shields.io/badge/L%C3%96VE-${{ needs.mirror_website.outputs.version }}-EA316E.svg?style=flat-square)`);
            fs.writeFileSync('README.md', readmeContent);
