name: Update README.md daily

on:
  schedule:
    - cron: '0 1 1 * *'
  workflow_dispatch:

jobs:
  remove_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Remove readme
        run: |
          rm README.md
          echo $(ls)
        
      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add *
          git commit -m "Automatic Remove of README.md"
          git push
          echo "Just fail don't notify me"

  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install Lua 5.4
        run: sudo apt-get install lua5.4 curl grep -y
        
      - name: Update README.md
        run: lua update_readme.lua
        
      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add README.md
          git commit -m "Automatic Update of README.md"
          git push
          echo "Just fail don't notify me"